name: 'Copy to Repository'
description: >
  Finds changed files in this push.
inputs:
  prefix_dir:
    description: The prefix dir where modules can be found
    required: true
outputs:
  modules:
    description: >
      JSON formatted array containing the changed modules
    value: ${{ steps.find_changed_modules.outputs.modules }}

runs:
  using: "composite"
  steps:
  - id: find_changed_modules
    shell: bash
    env:
      PREFIX_DIR: "${{ inputs.prefix_dir }}"

    run: |
      set -x
      git fetch origin \
          "${{ github.event.before }}" \
          "${{ github.event.after }}"
      modules=$(git -C "$PREFIX_DIR" diff --name-only --relative \
            "${{ github.event.before }}" \
            "${{ github.event.after }}" | \
          cut -d / -f 1 | \
          sort -u | \
          sed 's/"/\\"/g; s/.*/"&"/' | \
          paste -d, -s || true)
      echo "modules=[${modules}]" >> "$GITHUB_OUTPUT"
